<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Administer' => '',
    'Aid' => '',
    'Auth Key' => '',
    'Cid' => '',
    'Code' => '',
    'Config' => '',
    'Created At' => '',
    'Data Dir' => '',
    'Date' => '',
    'Did' => '',
    'Editor' => '',
    'Email' => '',
    'End Time' => '',
    'Event' => '',
    'Fingerprint' => '',
    'Flash' => '',
    'ID' => '',
    'Ic Card' => '',
    'Id Card' => '',
    'Info' => '',
    'Member' => '',
    'Mobile' => '',
    'Money' => '',
    'Name' => '',
    'Passwd' => '',
    'Password Reset Token' => '',
    'Position' => '',
    'Real Name' => '',
    'Role' => '',
    'Sex' => '',
    'Status' => '',
    'Type' => '',
    'Uid' => '',
    'Attendance Record' => '',
    'System' => '',
    'Toggle navigation' => '',
];
