<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Token' => '',
    'Auth Key' => '',
    'Cid' => '卡片ID',
    'Code' => '卡号',
    'Config' => '',
    'Cover' => '',
    'Editor' => '',
    'Event' => '操作',
    'Flash' => '',
    'Gid' => '',
    'Image' => '图片',
    'Password Reset Token' => '',
    'Uuid' => '访客用户ID',
    'Attendance Record' => '签到',
    'Attendances' => '签到数据',
    'MAIN NAVIGATION' => '主菜单',
    'System' => '系统',
    'Toggle navigation' => '',
    'Administer' => '管理员',
    'Aid' => '签到ID',
    'Created At' => '时间',
    'Data Dir' => '数据读取路径',
    'Date' => '日期',
    'Did' => '设备ID',
    'Email' => '邮箱',
    'End Time' => '结束时间',
    'Fingerprint' => '指纹信息',
    'ID' => 'ID',
    'Ic Card' => 'IC卡号',
    'Id Card' => '身份证号',
    'Info' => '信息',
    'Member' => '成员',
    'Mobile' => '手机号',
    'Money' => '余额',
    'Name' => '名称',
    'Passwd' => '密码',
    'Position' => '位置',
    'Real Name' => '真实姓名',
    'Role' => '角色',
    'Sex' => '性别',
    'Status' => '状态',
    'Type' => '类型',
    'Uid' => '用户ID',
    'Dashboard' => '操作面板',
    'Users' => '用户',
    'Create User' => '添加用户',
    'Devices' => '设备',
    'Create Device' => '添加设备',
    'Create Attendance' => '添加记录',
    'Guests' => '访客',
    'Create Guest' => '创建访客',
    'Ic Cards' => 'IC卡',
    'Create Ic Card' => '添加IC卡',
    'Face' => '面部识别',
    'Finger' => '指纹',
    'Card' => '刷卡',
    'Go away datetime' => '退签时间',
    'Total user number' => '总用户数',
    'Total device number' => '总设备数',
    'Today user attendance' => '今日签到人数',
    'Today guests num' => '今日访客人数',
    'Sign out' => '退出',
];
